[package]
name = "actix-udp-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ts_opentelemetry = { path = "../../../opentelemetry" }
ts_opentelemetry_jaeger = { path = "../.." }
actix-web = "4.1"
actix-service = "2"
env_logger = "0.9"
